name: Build Windows EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall selenium webdriver-manager pyinstaller

    - name: Build with PyInstaller
      run: pyinstaller --onefile --noconfirm --clean --collect-all selenium --collect-all webdriver_manager --hidden-import "selenium.webdriver.chrome.webdriver" --hidden-import "selenium.webdriver.chrome.service" --hidden-import "webdriver_manager.chrome" weather_forecast_2.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: dist/*.exe
